version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8082"  # Map external port 8081 to container port 8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/employee_directory?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Qaz123@
      SPRING_SECURITY_USER_NAME: ali
      SPRING_SECURITY_USER_PASSWORD: test123
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Qaz123@
      MYSQL_DATABASE: employee_directory
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: